##Assignment Question

1. What is TensorFlow 2.0, and how is it different from TensorFlow 1.x

=>  
##TensorFlow 2.0 vs TensorFlow 1.x
* API Cleanup: TensorFlow 2.0 removes redundant and duplicate APIs that existed in 1.x, leading to a more streamlined and consistent library.
* API Consistency: TensorFlow 2.0 makes APIs more consistent. Examples provided include unified RNNs and unified Optimizers, suggesting a more standardized way of building and training models.
* Functions over Sessions: TensorFlow 2.0 prefers using Python functions over the session-based execution model that was prominent in 1.x. This makes the code feel more like standard Python.
* Eager Execution by Default: In TensorFlow 2.0, Eager execution is enabled by default. Eager execution allows you to evaluate operations immediately, making debugging and development easier compared to the graph-based execution in TensorFlow 1.x where you had to build a graph and then run it in a session. TensorFlow 2.0 integrates better with the Python runtime due to this.

2. How do you install TensorFlow 2.0

=> The primary way to install TensorFlow 2.0 is by using Python's package manager, pip.

Here are the general steps:

Check System Requirements: Ensure your system meets the requirements. For example, Ubuntu 16.04 or higher (64-bit) is a requirement for the official packages [2]. You'll also need a supported Python version and pip version greater than 19.0

Create a Virtual Environment (Recommended): It's highly recommended to create a virtual environment to isolate your project dependencies. This helps avoid conflicts with other Python projects on your system.

3. What is the primary function of the tf.function in TensorFlow 2.0

=> he primary function of tf.function in TensorFlow 2.0 is to convert regular Python functions that use TensorFlow operations into a callable TensorFlow Graph.

4. What is the purpose of the Model class in TensorFlow 2.0

=> the primary purpose of the Model class in TensorFlow 2.0 (specifically within the Keras API, which is the recommended high-level API in TensorFlow 2.0) is to group layers and represent a model's architecture and training capabilities.

5. How do you create a neural network using TensorFlow 2.0

=> the primary purpose of the Model class in TensorFlow 2.0 (specifically within the Keras API, which is the recommended high-level API in TensorFlow 2.0) is to group layers and represent a model's architecture and training capabilities.

6. What is the importance of Tensor Space in TensorFlow

=>  Tensors are multi-dimensional arrays. Their shape explicitly defines the organization of the data within the tensor – how many dimensions it has (its rank) and how many elements are along each axis (or dimension). Without understanding the shape, you wouldn't know how your data is structured or how to access specific elements.



7. How can TensorBoard be integrated with TensorFlow 2.0

=> TensorFlow code in Python while still benefiting from the performance and deployment advantages of TensorFlow's graph execution. It's a key feature in TensorFlow 2.0 that promotes a balance between imperative programming and optimized graph-based execution.

8. What is the purpose of TensorFlow Playground

=>  TensorFlow Playground provides a hands-on environment where you can experiment with different neural network architectures, hyperparameters, and datasets without writing any code. This interactive approach makes it easier to grasp how neural networks learn and make predictions.

9. What is Netron, and how is it useful for deep learning models

=> The tool visually represents the neural network's structure, including its layers, neurons, and connections. As the network trains, you can observe how the weights and biases change and how the decision boundary evolves.

10. What is the difference between TensorFlow and PyTorch

=> TensorFlow deep learning library is developed by the Google Brain engineering team. It was open source licensed on the 2015 and has since then become very popular for its flexibility and also scalability. In essence, it is employed to roll out of the deep learning architectures.

 which has gained recognition for putting the things straightforward and also flexible. It was basically launched as an Open-Source Library for the purpose of training the deep learning algorithms in 2016. It is often applauded for its simplicity and also flexibility, which serves as a very powerful tool for the engineers whenever they want to do Debug and also experiment with some of the algorithms.

11. How do you install PyTorch

=> which has gained recognition for putting the things straightforward and also flexible. It was basically launched as an Open-Source Library for the purpose of training the deep learning algorithms in 2016. It is often applauded for its simplicity and also flexibility, which serves as a very powerful tool for the engineers whenever they want to do Debug and also experiment with some of the algorithms.

12. What is the basic structure of a PyTorch neural network

=> PyTorch neural network typically involves subclassing the torch.nn.Module class and defining the network's layers and forward pass.

13. What is the significance of tensors in PyTorch


=> the fundamental data structure in PyTorch. Their significance lies in being the central building blocks for all computations and operations within the framework.

14. What is the difference between torch.Tensor and torch.cuda.Tensor in PyTorch


=> PyTorch's automatic differentiation engine, Autograd, works directly with tensors. Tensors in PyTorch can track the operations performed on them and automatically compute gradients [1]. This is fundamental for backpropagation, the algorithm used to train neural networks by adjusting model parameters based on the gradients of the loss function. The ability of tensors to participate in gradient computation is a key differentiator from standard NumPy arrays.

15. What is the purpose of the torch.optim module in PyTorch

=> A major advantage of tensors in PyTorch is their ability to be moved to and computed on GPUs. This is crucial for accelerating the computationally intensive operations involved in training deep neural networks . Without tensors that can leverage GPU power, deep learning training would be significantly slower.

16. What are some common activation functions used in neural networks

=> PyTorch's tensors are tightly integrated with its eager execution and dynamic graph capabilities. You can define and manipulate tensors interactively, and the computation graph is built dynamically as you perform operations on them .

17. What is the difference between torch.nn.Module and torch.nn.Sequential in PyTorch

=> While the former defines nn.Module classes, the latter uses a functional (stateless) approach.
To dig a bit deeper: nn.Modules are defined as Python classes and have attributes, e.g. a nn.Conv2d module will have some internal attributes like self.weight. F.conv2d however just defines the operation and needs all arguments to be passed (including the weights and bias). Internally the modules will usually call their functional counterpart in the forward method somewhere.

18. How can you monitor training progress in TensorFlow 2.0

=> PyTorch tensors can be easily converted to and from NumPy arrays, making it convenient to work with existing NumPy-based code and data

19. How does the Keras API fit into TensorFlow 2.0

TensorFlow 2.0 officially adopted Keras as its primary high-level API. This means that when you install TensorFlow 2.0, Keras is automatically included and is the standard way to define and train models.

20. What is an example of a deep learning project that can be implemented using TensorFlow 2.0

=>  Keras provides user-friendly building blocks like Layers and Models [1]. This simplifies the process of creating complex neural network architectures by allowing you to stack or connect pre-defined layers. You don't need to deal with low-level TensorFlow operations as much when using Keras.

21. What is the main advantage of using pre-trained models in TensorFlow and PyTorch?

=> Training a deep neural network from scratch requires a significant amount of time and computational resources (GPUs). Pre-trained models have already learned powerful features from vast datasets (like ImageNet for image tasks). By using a pre-trained model, you can leverage these learned features and significantly reduce the time required to train your model on a new, smaller dataset.

##Practical Questions

1. How do you install and verify that TensorFlow 2.0 was installed successfully

In [1]:
#Code for the above Ques.
!pip install tensorflow

import tensorflow as tf
print(tf.__version__)

hello = tf.constant('Hello, TensorFlow!')
print(hello.numpy())

2.18.0
b'Hello, TensorFlow!'


2. How can you define a simple function in TensorFlow 2.0 to perform addition

In [2]:
#Code for the above Ques.
import tensorflow as tf

@tf.function
def add_numbers(a, b):

  return a + b

tensor_a = tf.constant([1, 2, 3])
tensor_b = tf.constant([4, 5, 6])

result_tensor = add_numbers(tensor_a, tensor_b)

print("Tensor A:", tensor_a)
print("Tensor B:", tensor_b)
print("Result of addition (tf.function):", result_tensor)

tensor_c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
tensor_d = tf.constant([[5.0, 6.0], [7.0, 8.0]])

result_float_tensor = add_numbers(tensor_c, tensor_d)

print("\nTensor C:", tensor_c)
print("Tensor D:", tensor_d)
print("Result of addition (tf.function with floats):", result_float_tensor)


Tensor A: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor B: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Result of addition (tf.function): tf.Tensor([5 7 9], shape=(3,), dtype=int32)

Tensor C: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Tensor D: tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
Result of addition (tf.function with floats): tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


3. How can you create a simple neural network in TensorFlow 2.0 with one hidden layer

In [3]:
#Code for the above Ques.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

model = Sequential([

    Flatten(input_shape=(28, 28)),

    Dense(128, activation='relu'),

    Dense(10, activation='softmax')
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()



/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

4. How can you visualize the training progress using TensorFlow and Matplotlib

In [1]:
#Code for the above Ques.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
import matplotlib.pyplot as plt
import numpy as np


num_samples = 1000
input_features = 20
num_classes = 2

x_train = np.random.rand(num_samples, input_features).astype(np.float32)
y_train = np.random.randint(0, num_classes, num_samples)


x_val = np.random.rand(int(num_samples * 0.2), input_features).astype(np.float32)
y_val = np.random.randint(0, num_classes, int(num_samples * 0.2))



model = Sequential([
    Dense(64, activation='relu', input_shape=(input_features,)),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax') # Output layer for classification
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=20, validation_data=(x_val, y_val), verbose=0)

loss = history.history['loss']
val_loss = history.history['val_loss']
accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


5. How do you install PyTorch and verify the PyTorch installation

In [6]:
#Code for the above Ques.
!pip install torch torchvision torchaudio

import torch
x = torch.rand(5, 3)
print(x)
print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_properties(0))
print(torch.cuda.get_device_capability(0))

tensor([[0.0958, 0.3345, 0.5593],
        [0.9000, 0.3881, 0.8339],
        [0.4458, 0.4412, 0.5447],
        [0.9843, 0.9871, 0.4115],
        [0.2644, 0.4433, 0.9991]])
False
12.4


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

6. How do you create a simple neural network in PyTorch

In [7]:
#Code for the above Ques.
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleNN, self).__init__()

        self.fc1 = nn.Linear(input_dim, hidden_dim)

        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):

        x = F.relu(self.fc1(x))

        out = self.fc2(x)

        return out


input_dim = 10
hidden_dim = 20
output_dim = 1

model = SimpleNN(input_dim, hidden_dim, output_dim)

print(model)

dummy_input = torch.randn(1, input_dim)

output = model(dummy_input)
print("\nDummy input shape:", dummy_input.shape)
print("Output shape:", output.shape)


dummy_data = torch.randn(100, input_dim)
dummy_labels = torch.randn(100, output_dim)

criterion = nn.MSELoss()

optimizer = optim.Adam(model.parameters(), lr=0.01)



SimpleNN(
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=1, bias=True)
)

Dummy input shape: torch.Size([1, 10])
Output shape: torch.Size([1, 1])


7. How do you define a loss function and optimizer in PyTorch

In [8]:
#Code for the above Ques.
import torch
import torch.nn as nn # For loss functions
import torch.optim as optim # For optimizers


criterion_mse = nn.MSELoss()
print("Defined MSE Loss Function:", criterion_mse)


Defined MSE Loss Function: MSELoss()


8. How do you implement a custom loss function in PyTorch


In [4]:
#Code for the above Ques.
import torch
import torch.nn as nn

def custom_mean_absolute_error(outputs, targets):

  if outputs.shape != targets.shape:
      raise ValueError("Outputs and targets must have the same shape")

  abs_diff = torch.abs(outputs - targets)

  mae_loss = torch.mean(abs_diff)

  return mae_loss

outputs = torch.randn(5, 1, requires_grad=True)
targets = torch.randn(5, 1)

loss = custom_mean_absolute_error(outputs, targets)

print("Outputs:", outputs)
print("Targets:", targets)
print("Custom MAE Loss:", loss)


Outputs: tensor([[-1.1486],
        [-1.4683],
        [-0.2754],
        [-0.2843],
        [ 1.5282]], requires_grad=True)
Targets: tensor([[ 0.4344],
        [-0.0587],
        [-0.0947],
        [-0.0288],
        [ 0.4725]])
Custom MAE Loss: tensor(0.8969, grad_fn=<MeanBackward0>)


9. How do you save and load a TensorFlow model

In [10]:
#Code for the above Ques.
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
import os # Import os module to create directories

model_save_dir = 'saved_model_example'
os.makedirs(model_save_dir, exist_ok=True)


# Define a simple model (as in previous examples)
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

saved_model_path = os.path.join(model_save_dir, 'my_saved_model.keras')

model.save(saved_model_path)
print(f"Model saved to: {saved_model_path}")

loaded_model = tf.keras.models.load_model(saved_model_path)
print("\nModel loaded successfully!")

loaded_model.summary()

Model saved to: saved_model_example/my_saved_model.keras

Model loaded successfully!


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 10 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305,312 (1.16 MB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 203,542 (795.09 KB)

You can install TensorFlow 2.0 using pip. It's generally recommended to use a virtual environment to avoid conflicts with other Python packages.

Here are the steps: